apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "--logging.level.ca.ubc={{ .Values.logging.level }}",
            "--canvas.url={{ .Values.canvas.url }}",
            "--canvas.token={{ .Values.canvas.token }}",
            "--canvas.timeout.connect={{ .Values.canvas.timeout.connect }}",
            "--canvas.timeout.read={{ .Values.canvas.timeout.read }}",
            "--server.ssl.enabled={{ .Values.server.ssl.enabled }}",
            {{- if .Values.server.useForwardHeaders }}
            "--server.use-forward-headers={{ .Values.server.useForwardHeaders }}",
            {{- end }}
            {{- if .Values.server.tomcat }}
            {{- if .Values.server.tomcat.remoteIpHeader }}
            "--server.tomcat.remote-ip-header={{ .Values.server.tomcat.remoteIpHeader }}",
            {{- end }}
            {{- end }}
            "--saml.sp.key-store={{ .Values.saml.sp.keyStore }}",
            "--saml.sp.key-store-password={{ .Values.saml.sp.keyStorePassword }}",
            "--saml.sp.key-name={{ .Values.saml.sp.keyName }}",
            "--saml.sp.key-password={{ .Values.saml.sp.keyPassword }}",
            "--saml.sp.entityId={{ .Values.saml.sp.entityId }}",
            "--saml.sp.entityBaseUrl={{ .Values.saml.sp.entityBaseUrl }}",
            "--saml.idp.metadata.uri={{ .Values.saml.idp.metadataUri }}",
            "--saml.idp.attribute.puid={{ .Values.saml.idp.attribute.puid }}",
            "--saml.lb.scheme={{ .Values.saml.lb.scheme }}",
            "--saml.lb.serverName={{ .Values.saml.lb.serverName }}",
            "--saml.lb.serverPort={{ .Values.saml.lb.serverPort }}",
            "--saml.lb.contextPath={{ .Values.saml.lb.contextPath }}",
            "--saml.lb.includeServerPortInRequestURL={{ .Values.saml.lb.includeServerPortInRequestURL }}",
            "--saml.logging.messages={{ .Values.saml.logging.messages }}",
            "--ltps.v1.url={{ .Values.ltps.v1.url }}",
            "--ltps.v1.username={{ .Values.ltps.v1.username }}",
            "--ltps.v1.password={{ .Values.ltps.v1.password }}",
            "--ltps.v2.url={{ .Values.ltps.v2.url }}",
            "--ltps.v2.username={{ .Values.ltps.v2.username }}",
            "--ltps.v2.password={{ .Values.ltps.v2.password }}",
            "--config.reconEnabled={{ .Values.config.reconEnabled }}",
            {{- if and .Values.devmode.enabled .Values.devmode.puid }}
            "--devMode.puid={{ .Values.devmode.puid }}"
            {{- end }}
          ]
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: {{ template "fullname" . }}-persistent-storage
            mountPath: /data
          {{- end }}
          - name: {{ template "fullname" . }}-config
            mountPath: /config
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: {{ template "fullname" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- end }}
      - name: {{ template "fullname" . }}-config
        configMap:
          name: {{ template "fullname" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
