apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.vault.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vault.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.canvas.vault.token_secret }}
      remoteRef:
        key: {{ .Values.vault.path }}
        property: {{ .Values.canvas.vault.token_secret }}
    - secretKey: {{ .Values.saml.sp.vault.key_secret }}
      remoteRef:
        key: {{ .Values.vault.path }}
        property: {{ .Values.saml.sp.vault.key_secret }}
    - secretKey: {{ .Values.saml.sp.vault.keystore_secret }}
      remoteRef:
        key: {{ .Values.vault.path }}
        property: {{ .Values.saml.sp.vault.keystore_secret }}
    - secretKey: {{ .Values.ltps.v1.vault.password_secret }}
      remoteRef:
        key: {{ .Values.vault.path }}
        property: {{ .Values.ltps.v1.vault.password_secret }}
    - secretKey: {{ .Values.ltps.v2.vault.password_secret }}
      remoteRef:
        key: {{ .Values.vault.path }}
        property: {{ .Values.ltps.v2.vault.password_secret }}


