apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.CI_PIPELINE_ID }}
    autodeployed: "true"
    pipeline_id: "{{  .Values.CI_PIPELINE_ID }}"
    {{- end }}
    {{- if .Values.CI_BUILD_ID }}
    build_id: "{{ .Values.CI_BUILD_ID }}"
    {{- end }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      stage: {{ .Values.stage }}
      tier: worker
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        stage: {{ .Values.stage }}
        tier: worker
    spec:
      containers:
      - name: {{ .Chart.Name }}-worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command: ["celery", "--app=celery_worker.celery", "worker", "--loglevel=INFO"]
        env:
        - name: DB_HOST
          value: "{{ template "fullname" . }}-db"
        - name: DB_PORT
          value: {{ .Values.dbPort | quote }}
        - name: DB_USERNAME
          value: {{ .Values.dbUsername | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql_password
        - name: DB_NAME
          value: {{ .Values.dbName | quote }}
        - name: DB_CONN_OPTIONS
          value: {{ .Values.dbConnOptions | squote }}
        - name: CELERY_BROKER_URL
          value: "redis://{{ template "fullname" . }}-redis:{{ .Values.redis.service.port }}"
        - name: ATTACHMENT_UPLOAD_LIMIT
          value: {{ .Values.attachment.uploadLimit | quote }}
        - name: ATTACHMENT_ALLOWED_EXTENSIONS
          value: {{ .Values.attachment.allowedExtensions | quote }}
        - name: ATTACHMENT_PREVIEW_EXTENSIONS
          value: {{ .Values.attachment.previewExtensions | quote }}
        - name: APP_LOGIN_ENABLED
          value: {{ .Values.appLoginEnabled | quote }}
        - name: LTI_LOGIN_ENABLED
          value: {{ .Values.ltiLoginEnabled | quote }}
        - name: CAS_LOGIN_ENABLED
          value: {{ .Values.cas.enabled | quote }}
        - name: CAS_GLOBAL_UNIQUE_IDENTIFIER_FIELD
          value: {{ .Values.cas.globalUniqueIdentifierField | quote }}
        {{- if .Values.cas.enabled }}
        - name: CAS_SERVER
          value: {{ .Values.cas.server | quote }}
        - name: CAS_AUTH_PREFIX
          value: {{ .Values.cas.authPrefix | quote }}
        - name: CAS_USE_SAML
          value: {{ .Values.cas.useSAML | quote }}
        - name: CAS_ATTRIBUTE_USER_ROLE
          value: {{ .Values.cas.attributeUserRole | quote }}
        - name: CAS_INSTRUCTOR_ROLE_VALUES
          value: {{ .Values.cas.instructorRoleValues | quote }}
        - name: CAS_ATTRIBUTE_FIRST_NAME
          value: {{ .Values.cas.attributeFirstName | quote }}
        - name: CAS_ATTRIBUTE_LAST_NAME
          value: {{ .Values.cas.attributeLastName | quote }}
        - name: CAS_ATTRIBUTE_STUDENT_NUMBER
          value: {{ .Values.cas.attributeStudentNumber | quote }}
        - name: CAS_ATTRIBUTE_EMAIL
          value: {{ .Values.cas.attributeEmail | quote }}
        {{- if .Values.cas.loginHTML }}
        - name: CAS_LOGIN_HTML
          value: {{ .Values.cas.loginHTML | quote }}
        {{- end }}
        {{- end }}
        - name: SAML_LOGIN_ENABLED
          value: {{ .Values.saml.enabled | quote }}
        - name: SAML_UNIQUE_IDENTIFIER
          value: {{ .Values.saml.uniqueIdentifier | quote }}
        - name: SAML_GLOBAL_UNIQUE_IDENTIFIER_FIELD
          value: {{ .Values.saml.globalUniqueIdentifierField | quote }}
        {{- if .Values.saml.enabled }}
        - name: SAML_SETTINGS_FILE
          value: {{ .Values.saml.settingsFile | quote }}
        {{- if .Values.saml.settings }}
        - name: SAML_SETTINGS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: saml_settings
        {{- end }}
        - name: SAML_METADATA_URL
          value: {{ .Values.saml.metadataUrl | quote }}
        - name: SAML_METADATA_ENTITY_ID
          value: {{ .Values.saml.metadataEntityId | quote }}
        - name: SAML_EXPOSE_METADATA_ENDPOINT
          value: {{ .Values.saml.exposeMetadataEndpoint | quote }}
        - name: SAML_ATTRIBUTE_USER_ROLE
          value: {{ .Values.saml.attributeUserRole | quote }}
        - name: SAML_INSTRUCTOR_ROLE_VALUES
          value: {{ .Values.saml.instructorRoleValues | quote }}
        - name: SAML_ATTRIBUTE_FIRST_NAME
          value: {{ .Values.saml.attributeFirstName | quote }}
        - name: SAML_ATTRIBUTE_LAST_NAME
          value: {{ .Values.saml.attributeLastName | quote }}
        - name: SAML_ATTRIBUTE_STUDENT_NUMBER
          value: {{ .Values.saml.attributeStudentNumber | quote }}
        - name: SAML_ATTRIBUTE_EMAIL
          value: {{ .Values.saml.attributeEmail | quote }}
        {{- if .Values.saml.loginHTML }}
        - name: SAML_LOGIN_HTML
          value: {{ .Values.saml.loginHTML | quote }}
        {{- end }}
        {{- end }}
        - name: XAPI_ENABLED
          value: {{ .Values.lrs.xapi.enabled | quote }}
        {{- if .Values.lrs.xapi.enabled }}
        - name: LRS_XAPI_STATEMENT_ENDPOINT
          value: {{ .Values.lrs.xapi.statementEndpoint | quote }}
        - name: LRS_XAPI_USERNAME
          value: {{ .Values.lrs.xapi.username | quote }}
        {{- if .Values.lrs.xapi.password }}
        - name: LRS_XAPI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: xapi_password
        {{- end }}
        {{- end }}
        - name: CALIPER_ENABLED
          value: {{ .Values.lrs.caliper.enabled | quote }}
        {{- if .Values.lrs.caliper.enabled }}
        - name: LRS_CALIPER_HOST
          value: {{ .Values.lrs.caliper.host | quote }}
        {{- if .Values.lrs.caliper.api_key }}
        - name: LRS_CALIPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: caliper_api_key
        {{- end }}
        {{- end }}
        - name: LRS_APP_BASE_URL
          value: {{ .Values.lrs.appBaseURL | quote }}
        - name: LRS_ACTOR_ACCOUNT_USE_GLOBAL_UNIQUE_IDENTIFIER
          value: {{ .Values.lrs.actorAccountUseGlobalUniqueIdentifier | quote }}
        - name: LRS_ACTOR_ACCOUNT_GLOBAL_UNIQUE_IDENTIFIER_HOMEPAGE
          value: {{ .Values.lrs.actorAccountGlobalUniqueIdentifierHomepage | quote }}
        - name: LRS_USER_INPUT_FIELD_SIZE_LIMIT
          value: {{ .Values.lrs.userInputFieldSizeLimit | quote }}
        - name: ASSET_LOCATION
          value: {{ .Values.assetLocation | quote }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: secret_key
        - name: C_FORCE_ROOT
          value: {{ .Values.cForceRoot | quote }}
        - name: ENFORCE_SSL
          value: {{ .Values.enforceSSL | quote }}
        - name: DEMO_INSTALLATION
          value: {{ .Values.demoInstance | quote }}
        - name: CELERY_TIMEZONE
          value: {{ .Values.celery.timezone | quote }}
        - name: CELERY_WORKER_MAX_MEMORY_PER_CHILD
          value: {{ .Values.celery.workerMaxMemoryPerChild | quote }}
        - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
          value: {{ .Values.celery.workerMaxTasksPerChild | quote }}
        - name: CELERY_TASK_ALWAYS_EAGER
          value: {{ .Values.celery.taskAlwaysEager | quote }}
        - name: MAIL_NOTIFICATION_ENABLED
          value: {{ .Values.mail.enabled | quote }}
        {{- if .Values.mail.enabled }}
        - name: MAIL_SERVER
          value: {{ .Values.mail.server | quote }}
        - name: MAIL_PORT
          value: {{ .Values.mail.port | quote }}
        - name: MAIL_USE_SSL
          value: {{ .Values.mail.useSSL | quote }}
        - name: MAIL_USE_TLS
          value: {{ .Values.mail.useTLS | quote }}
        - name: MAIL_USERNAME
          value: {{ .Values.mail.username | quote }}
        {{- if .Values.mail.password }}
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mail_password
        {{- end }}
        - name: MAIL_DEFAULT_SENDER
          value: {{ .Values.mail.defaultSender | quote }}
        {{- end }}
        - name: KALTURA_ENABLED
          value: {{ .Values.kaltura.enabled | quote }}
        - name: KALTURA_USE_GLOBAL_UNIQUE_IDENTIFIER
          value: {{ .Values.kaltura.useGlobalUniqueIdentifier | quote }}
        {{- if .Values.kaltura.enabled }}
        - name: KALTURA_SERVICE_URL
          value: {{ .Values.kaltura.serviceURL | quote }}
        - name: KALTURA_PARTNER_ID
          value: {{ .Values.kaltura.partnerId | quote }}
        {{- if .Values.kaltura.secret }}
        - name: KALTURA_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: kaltura_secret
        {{- end }}
        - name: KALTURA_USER_ID
          value: {{ .Values.kaltura.userId | quote }}
        - name: KALTURA_PLAYER_ID
          value: {{ .Values.kaltura.playerId | quote }}
        - name: KALTURA_VIDEO_EXTENSIONS
          value: {{ .Values.kaltura.videoExtensions | quote }}
        - name: KALTURA_AUDIO_EXTENSIONS
          value: {{ .Values.kaltura.audioExtensions | quote }}
        {{- end }}
        - name: EXPOSE_EMAIL_TO_INSTRUCTOR
          value: {{ .Values.expose.emailToInstructor | quote }}
        - name: EXPOSE_CAS_USERNAME_TO_INSTRUCTOR
          value: {{ .Values.expose.casUsernameToInstructor | quote }}
        - name: ALLOW_STUDENT_CHANGE_NAME
          value: {{ .Values.allowStudentChange.name | quote }}
        - name: ALLOW_STUDENT_CHANGE_DISPLAY_NAME
          value: {{ .Values.allowStudentChange.displayName | quote }}
        - name: ALLOW_STUDENT_CHANGE_STUDENT_NUMBER
          value: {{ .Values.allowStudentChange.studentNumber | quote }}
        - name: ALLOW_STUDENT_CHANGE_EMAIL
          value: {{ .Values.allowStudentChange.email | quote }}
        - name: GA_TRACKING_ID
          value: {{ .Values.gaTrackingId | quote }}
        {{- if .Values.loginAdditionalInstructionsHTML }}
        - name: LOGIN_ADDITIONAL_INSTRUCTIONS_HTML
          value: {{ .Values.loginAdditionalInstructionsHTML | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.worker.resources | indent 10 }}
      {{- if .Values.app.persistence.enabled }}
        volumeMounts:
        - name: {{ template "fullname" . }}-persistent-storage
          mountPath: /code/persistent
      volumes:
      - name: {{ template "fullname" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-app-pvc
      {{- end }}
