{{- if .Values.app.persistence.enabled }}
  {{- if not .Values.app.persistence.storageClass }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "compair.fullname" . }}-app-pv
  annotations:
    {{- range $key, $value := .Values.app.persistence.annotations }}
      {{ $key  }}: {{ $value | quote  }}
    {{- end }}
  labels:
    {{- include "compair.labels" . | nindent 4 }}
    tier: filestore
spec:
  accessModes:
    - {{ .Values.app.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.app.persistence.size | quote }}
  storageClassName: ""
{{ toYaml .Values.app.persistence.resources | indent 2 }}

---
  {{- end }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "compair.fullname" . }}-app-pvc
  {{- if or .Values.app.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.app.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "compair.labels" . | nindent 4 }}
    tier: filestore
spec:
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.app.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}

---
{{- end }}

{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "compair.fullname" . }}-redis-pvc
  {{- if or .Values.redis.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.redis.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "compair.labels" . | nindent 4 }}
    tier: redis
spec:
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.redis.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}
