apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compair.fullname" . }}
  labels:
    {{- include "compair.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secretKey }}
  secret_key: {{ default "" .Values.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.saml.settings }}
  saml_settings: {{ default "" .Values.saml.settings | b64enc | quote }}
  {{- end }}
  {{- if .Values.lrs.xapi.password }}
  xapi_password: {{ default "" .Values.lrs.xapi.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.lrs.caliper.api_key }}
  caliper_api_key: {{ default "" .Values.lrs.caliper.api_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.mail.password }}
  mail_password: {{ default "" .Values.mail.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.kaltura.secret }}
  kaltura_secret: {{ default "" .Values.kaltura.secret | b64enc | quote }}
  {{- end }}
