{{- if or .Values.secretKey .Values.saml.settings .Values.lrs.xapi.password .Values.lrs.caliper.api_key .Values.mail.password .Values.kaltura.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compair.fullname" . }}
  labels:
    {{- include "compair.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secretKey }}
  secret_key: {{ .Values.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.saml.settings }}
  saml_settings: {{ .Values.saml.settings | b64enc | quote }}
  {{- end }}
  {{- if .Values.lrs.xapi.password }}
  xapi_password: {{ .Values.lrs.xapi.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.lrs.caliper.api_key }}
  caliper_api_key: {{ .Values.lrs.caliper.api_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.mail.password }}
  mail_password: {{ .Values.mail.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.kaltura.secret }}
  kaltura_secret: {{ .Values.kaltura.secret | b64enc | quote }}
  {{- end }}
{{- end }}
