apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.CI_PIPELINE_ID }}
    autodeployed: "true"
    pipeline_id: "{{  .Values.CI_PIPELINE_ID }}"
    {{- end }}
    {{- if .Values.CI_BUILD_ID }}
    build_id: "{{ .Values.CI_BUILD_ID }}"
    {{- end }}
type: Opaque
data:
  {{- if .Values.dbPassword }}
  mysql_password: {{ default "" .Values.dbPassword | b64enc | quote }}
  {{- else }}
  mysql_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretKey }}
  secret_key: {{ default "" .Values.secretKey | b64enc | quote }}
  {{- else }}
  secret_key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.saml.settings }}
  saml_settings: {{ default "" .Values.saml.settings | b64enc | quote }}
  {{- end }}
  {{- if .Values.lrs.xapiPassword }}
  lrs_password: {{ default "" .Values.lrs.xapiPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.mail.password }}
  mail_password: {{ default "" .Values.mail.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.kaltura.secret }}
  kaltura_secret: {{ default "" .Values.kaltura.secret | b64enc | quote }}
  {{- end }}