apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "responsemap.fullname" . }}-db
  labels:
    {{- include "responsemap.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "responsemap.fullname" . }}-db
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "responsemap.fullname" . }}-db
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          volumeMounts:
            - name: responsemap-db
              mountPath: /var/lib/mysql
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.db.rootPass }}
            - name: MARIADB_DATABASE
              value: {{ .Values.db.name }}
            - name: MARIADB_USER
              value: {{ .Values.db.user }}
            - name: MARIADB_PASSWORD
              value: {{ .Values.db.pass }}
            {{- if .Values.db.autoUpgrade }}
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            {{- end }}
      volumes:
        - name: responsemap-db
          persistentVolumeClaim:
            claimName: {{ include "responsemap.fullname" . }}-db-pvc
