kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "responsemap.fullname" . }}-upload-pvc
  labels:
    {{- include "responsemap.labels" . | nindent 4 }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}
