apiVersion: v1
kind: Service
metadata:
  name: {{ include "responsemap.fullname" . }}-db
  labels:
    {{- include "responsemap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app.kubernetes.io/name: {{ include "responsemap.fullname" . }}-db
