{{- if .Values.app.phpfpm.pmMaxChildren }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipeer.fullname" . }}-phpfpm-config
  labels:
    {{- include "ipeer.labels" . | nindent 4 }}
data:
  zzz-fpm-override.conf: |
    [www]
    pm.max_children = {{ .Values.app.phpfpm.pmMaxChildren }}
{{- end }}
