apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mediawiki.fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  db_user: {{ .Values.db.mysqlUser | b64enc | quote }}
  {{- if .Values.db.mysqlPassword }}
  db_password: {{ .Values.db.mysqlPassword | b64enc | quote }}
  {{- else }}
  db_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.adminPassword }}
  mediawiki_password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  mediawiki_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  smtp_password: {{ default "" .Values.smtpPassword | b64enc | quote }}
  {{- if .Values.ldap.enabled }}
  ldap_proxy_password: {{ default "" .Values.ldap.proxyPassword | b64enc | quote }}
  {{- end }}
