# Default values for statspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
stage: dev

adminEmail: admin@example.com
adminFirstName: DSpace
adminLastName: Admin
adminPassword: admin123
adminLanguage: en

image:
  repository: ubcctlt/dspace
  tag: statspace
  pullPolicy: Always
persistence:
  enabled: false
#  accessMode: ReadWriteOnce
#  size: 10Gi
#  resources:
#    nfs:
#      server: 10.1.1.1
#      path: "/export/data/dspace"
service:
  name: statspace
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts: []
    # if there are multiple host names, first one will be the primary.
    # - statspace.example.local
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
dspace:
  name: Dspace
  email:
    host: smtp.example.com
    port: 25
    username: ""
    password: ""
    from: admin@example.com
    feedback: admin@example.com
    admin: admin@example.com
    alert: admin@example.com
    registration: admin@example.com
  opensearch:
    shortname: Dspace
    longname: Dspace
    description: Dspace
  auth:
    # password auth configs
    domainValid:
    loginGroup:
    digestAlgorithm:
  searchRequestProcessor: org.dspace.app.webui.discovery.DiscoverySearchRequestProcessor
  handle:
    prefix: "123456789"
  recent:
    submissions:
      count: 0
  findCollectionOptimize: false
  webui:
    browseIndexs:
      - dateissued:item:dateissued
      - author:metadata:dc.contributor.*,dc.creator:text
      - title:item:title
      - subject:metadata:dc.subject.*:text
    sortOptions:
      - title:dc.title:title
      - dateissued:dc.date.issued:date
      - dateaccessioned:dc.date.accessioned:date
    itemlistColumns: >
      dc.date.issued(date),
      dc.title,
      dc.contributor.*
    collectionhome:
      useDateaccessioned: "true"
      browseName: title
    itemThumbnail:
      show: true
  #googleAnalyticsKey: UA-XXXXXX-X
  commenting:
    enabled: false
    deleteCuratorEmail: admin@example.com
    commentPerPage: 5
    titleMaxLength: 120
    detailMaxLength: 10000
    maxCommentPerItem: 10000
    policyURL: "http://www.hr.ubc.ca/respectful-environment/"

# database setup, https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md

postgresql:
  # enable the build in Postgres database. Set to false to use external db.
  # If "enabled" is set to false, the values below still in effect and will
  # be used for external database
  enabled: true
  # DB name and username has to be same, otherwise, migration script will throw error on startup.
  # admin password to be used to create postgres user and db
  postgresUser: postgres
  postgresPassword: postgres
  postgresDatabase: statspace
  # for some reason, it doesn't like to use statspace as username and pwd. so avoid to use them
  dbUser: dspace
  dbPassword: dspace

  service:
    # service name of postgres. When postgres.enabled is set to true. This should be commented
    # out as the service name will be set automatically as "postgresql.fullname".
    # When using  external db, this has to be set.
    #name:
    port: 5432
