apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "operations-hub.fullname" . }}-db
  labels:
    {{- include "operations-hub.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "operations-hub.fullname" . }}-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.db.secret.path }}
        property: {{ .Values.db.secret.usernameKey }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.db.secret.path }}
        property: {{ .Values.db.secret.passwordKey }}
