{{- if .Values.app.flask.secret.path }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "operations-hub.fullname" . }}-app
  labels:
    {{- include "operations-hub.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "operations-hub.fullname" . }}-app
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: {{ .Values.app.flask.secret.path }}
        property: {{ .Values.app.flask.secret.key }}
{{- end }}
