apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipeer.fullname" . }}
  {{- include "ipeer.namespace" . | nindent 2 }}
  labels:
    {{- include "ipeer.labels" . | nindent 4 }}
data:
  IPEER_AUTH_METHOD: {{ .Values.ipeer.auth_mode | quote }}
  {{- if eq .Values.ipeer.auth_mode "saml" }}
  IPEER_SAML_SP_PRIVATE_KEY: {{ printf "%s/%s" .Values.ipeer.saml.serviceProvider.certMountPath .Values.ipeer.saml.serviceProvider.keyFilename | quote }}
  IPEER_SAML_SP_CERTIFICATE: {{ printf "%s/%s" .Values.ipeer.saml.serviceProvider.certMountPath .Values.ipeer.saml.serviceProvider.certFilename | quote }}
  IPEER_SAML_SP_BASE_URL: {{ .Values.ipeer.saml.serviceProvider.baseUrl | quote }}
  IPEER_SAML_SP_ENTITY_ID: {{ .Values.ipeer.saml.serviceProvider.entityId | quote }}
  IPEER_SAML_ATTR_MAPPING: {{ .Values.ipeer.saml.serviceProvider.attributeMapping | quote }}
  IPEER_SAML_IDP_METADATA_URL: {{ .Values.ipeer.saml.idProvider.metadataUrl | quote }}
  IPEER_SAML_PROVIDER_FRIENDLY_NAME: {{ .Values.ipeer.saml.idProvider.friendlyName | quote }}
  {{- end }}
  # Arbitrary non-sensitive env vars from values.yaml env.*
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
