apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ipeer.fullname" . }}
  {{- include "ipeer.namespace" . | nindent 2 }}
  labels:
    {{- include "ipeer.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
  target:
    name: {{ include "ipeer.fullname" . }}
    creationPolicy: Owner
  data:
    {{- if .Values.externalSecret.data }}
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
    {{- end }}
    {{- if eq .Values.ipeer.auth_mode "saml" }}
    - secretKey: {{ .Values.ipeer.saml.serviceProvider.keySecretKey }}
      remoteRef:
        key: {{ .Values.ipeer.saml.serviceProvider.externalSecretPath }}
        property: {{ .Values.ipeer.saml.serviceProvider.externalSecretKeyProperty }}
    - secretKey: {{ .Values.ipeer.saml.serviceProvider.certSecretKey }}
      remoteRef:
        key: {{ .Values.ipeer.saml.serviceProvider.externalSecretPath }}
        property: {{ .Values.ipeer.saml.serviceProvider.externalSecretCertProperty }}
    {{- end }}
