apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipeer.fullname" . }}-nginx
  {{- include "ipeer.namespace" . | nindent 2 }}
  labels:
    {{- include "ipeer.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        location /static/ {
            alias /static/;
        }
    }
