apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipeer.fullname" . }}-app
  {{- include "ipeer.namespace" . | nindent 2 }}
  labels:
    {{- include "ipeer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: static
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/component: app
    {{- include "ipeer.selectorLabels" . | nindent 4 }}
