apiVersion: v2
name: mediawiki
version: 0.8.3
appVersion: 1.43.4
description: Extremely powerful, scalable software and a feature-rich wiki implementation
  that uses PHP to process and display data stored in a database.
keywords:
- mediawiki
- wiki
- http
- php
home: http://www.mediawiki.org/
sources:
- https://github.com/ubc/mediawiki-docker
maintainers:
- name: Pan Luo
  email: pan.luo@ubc.ca

dependencies:
- name: mariadb
  version: 22.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: db.disableExternal
  alias: db
