name: mediawiki
version: 0.5.22
appVersion: 1.31.0
description: Extremely powerful, scalable software and a feature-rich wiki implementation
  that uses PHP to process and display data stored in a database.
keywords:
- mediawiki
- wiki
- http
- php
home: http://www.mediawiki.org/
icon: https://bitnami.com/assets/stacks/mediawiki/img/mediawiki-stack-220x234.png
sources:
- https://github.com/ubc/mediawiki-docker
maintainers:
- name: Pan Luo
  email: pan.luo@ubc.ca
engine: gotpl
