{{- if .Values.workerSchedulerEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "github-learning-ubc.fullname" . }}-worker-scheduler
  labels:
    app: {{ template "github-learning-ubc.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.CI_PIPELINE_ID }}
    autodeployed: "true"
    pipeline_id: "{{  .Values.CI_PIPELINE_ID }}"
    {{- end }}
    {{- if .Values.CI_BUILD_ID }}
    build_id: "{{ .Values.CI_BUILD_ID }}"
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "github-learning-ubc.fullname" . }}
        stage: {{ .Values.stage }}
        tier: worker
    spec:
      {{- if .Values.worker.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.worker.image.pullSecret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-worker-scheduler
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command: ["celery", "beat", "--app=glu.celery_worker.celery", "--loglevel=INFO"]
        env:
        {{- include "glu.environment" . | indent 8 }}
        - name: C_FORCE_ROOT
          value: {{ .Values.cForceRoot | quote }}
{{- end }}
