apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cardscanner.fullname" . }}-web
  labels:
    {{- include "cardscanner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "cardscanner.fullname" . }}-web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cardscanner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        component: {{ include "cardscanner.fullname" . }}-web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cardscanner.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /up
              port: http
            initialDelaySeconds: 300
            periodSeconds: 300
          readinessProbe:
            httpGet:
              path: /up
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 18
          env:
            - name: APP_SERVICE
              value: {{ include "cardscanner.fullname" . }}
          volumeMounts:
            - name: cardscanner-app-public
              mountPath: /app/public
              readOnly: true
            - name: cardscanner-app-storage
              mountPath: /app/storage/app
              readOnly: true
            - name: default-conf
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
      volumes:
        - name: cardscanner-app-storage
          persistentVolumeClaim:
            claimName: {{ template "cardscanner.fullname" . }}-storage-pvc
        - name: cardscanner-app-public
          persistentVolumeClaim:
            claimName: {{ template "cardscanner.fullname" . }}-public-pvc
        - name: default-conf
          configMap:
            name: {{ template "cardscanner.fullname" . }}
            items:
            - key: nginx-conf-template
              path: default.conf.template
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

