apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cardscanner.fullname" . }}-worker
  labels:
    {{- include "cardscanner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "cardscanner.fullname" . }}-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cardscanner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        component: {{ include "cardscanner.fullname" . }}-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cardscanner.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ['php', 'artisan', 'queue:listen']
          env:
            - name: APP_NAME
              value: {{ .Values.app.name | quote }}
            - name: APP_ENV
              value: {{ .Values.app.env | quote }}
            - name: APP_KEY
              value: {{ .Values.app.key | quote }}
            - name: APP_DEBUG
              value: {{ .Values.app.debug | quote }}
            - name: APP_TIMEZONE
              value: {{ .Values.app.timezone | quote }}
            - name: APP_URL
              value: {{ .Values.app.url | quote }}
            - name: APP_PORT
              value: {{ .Values.app.port | quote }}
            - name: BCRYPT_ROUNDS
              value: {{ .Values.app.bcryptRounds | quote }}
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | quote }}
            - name: DB_DATABASE
              value: {{ .Values.db.name | quote }}
            - name: DB_USERNAME
              value: {{ .Values.db.name | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.db.pass | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
