# Default values for lti-shim
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mode: staging

image:
  repository: lthub/lti-shim
  tag: latest
  pullPolicy: Always

ingress:
  annotations:
    # To enable https, uncomment the following line
    kubernetes.io/tls-acme: "true"
    # This is for disabling https, comment these to enable https
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #kubernetes.io/tls-acme: "false"
  # if gitlab CI didn't provide a host, will use this host instead
  host: lti-shim.ubc.ca

app:
  key: "base64:DYF0KhMD6pA9kWeovg1SL8gapmoHF6hZmV1UK3GYhUY="

ltijs:
  image: lthub/ltijs-demo:2020-07-29
  host: ltijs.lti-shim.ubc.ca
  port: 80
  ltiKey: NotSureWhatThisIsForButItNeedsSomethingHere
  db:
    image: mongo:4
    port: 27017
    name: lti-shim-ltijs-db
    user: lti-shim-ltijs-db-user
    pass: lti-shim-ltijs-db-pass
  platform:
    url: https://lti-shim.ubc.ca
    name: LTI Shim
    clientId: "1"
    authEndpoint: https://lti-shim.ubc.ca/lti/launch/platform/auth
    accessTokenEndpoint: https://lti-shim.ubc.ca/lti/security/platform/token
    jwksEndpoint: https://lti-shim.ubc.ca/lti/platform/jwks

postgres:
  host: postgres
  port: 5432
  database: postgres
  username: postgres
  password: postgres

admin:
  name: admin
  email: "admin@example.com"
  password: password


