{{ if .Values.shib.sp.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zoom-captions.fullname" . }}-shibd
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  shib_sp_cert: {{ .Values.shib.sp.cert | b64enc | quote }}
  shib_sp_key: {{ .Values.shib.sp.key | b64enc | quote }}

---
{{- end }}
