apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zoom-captions.fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.db.db.password }}
  db_password: {{ .Values.db.db.password | b64enc | quote }}
  {{- else }}
  db_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

{{ if .Values.shib.sp.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zoom-captions.fullname" . }}-shibd
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  sp-cert.pem: {{ .Values.shib.sp.cert | b64enc | quote }}
  sp-key.pem: {{ .Values.shib.sp.key | b64enc | quote }}
{{- end }}
