apiVersion: v1
kind: Service
metadata:
  name: {{ include "zoom-captions.fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "zoom-captions.fullname" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "zoom-captions.fullname" . }}-shibd
  labels:
    {{- include "common_labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 1600
    targetPort: 1600
    protocol: TCP
    name: shibd
  selector:
    app: {{ template "zoom-captions.fullname" . }}-shibd