apiVersion: v1
kind: Service
metadata:
  name: {{ template "mattermost.fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
    tier: service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "mattermost.name" . }}
    release: {{ .Release.Name }}
