---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hotcrp.fullname" . }}-msmtp
data:
  msmtprc: |-
    defaults
    logfile        /var/log/msmtp.log

    account default
    host {{ .Values.smtp.host }}
    port {{ .Values.smtp.port }}
    {{- if .Values.smtp.username }}
    user {{ .Values.smtp.username }}
    {{- end }}
    {{- if .Values.smtp.password}}
    password {{ .Values.smtp.password }}
    {{- end }}


{{- if .Values.ingress.enabled }}
---
{{- $fullName := include "hotcrp.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-ingress-cm
data:
  SCRIPT_FILENAME: "/var/www/html/index.php"
  SCRIPT_NAME: "/index.php"
  PATH_INFO: "$fastcgi_path_info"
{{- end }}
