{{- if .Values.hotcrp.persistence.enabled -}}
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hotcrp.fullname" . }}-app-log
  labels:
    {{- include "hotcrp.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.hotcrp.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.hotcrp.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.hotcrp.persistence.log.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.hotcrp.persistence.log.size | quote }}
  storageClassName: {{ .Values.hotcrp.persistence.log.storageClass | quote }}
{{- end -}}
