{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "moodle.fullname" . }}-cronjob
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
    tier: app
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- if .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  {{- end }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      {{- if .Values.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      {{- end }}
      template:
        spec:
          containers:
          - name: {{ include "moodle.fullname" . }}
              {{- include "moodle.app.spec" . | indent 12 }}
            command:
            - /bin/sh
            - -c
            - /usr/bin/sudo -E -u www-data /usr/local/bin/php admin/cli/cron.php
          restartPolicy: OnFailure
          volumes:
            {{- include "moodle.app.mounts" . | indent 12 }}
{{- end }}
