{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.storageClass }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "moodle.fullname" . }}-app-pv
  labels:
    {{- include "common_labels" . | indent 4 }}
    tier: filestore
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- if .Values.persistence.resources }}
{{ toYaml .Values.persistence.resources | indent 2 }}
{{- end }}
{{- end }}
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "moodle.fullname" . }}-app-pvc
  labels:
    {{- include "common_labels" . | indent 4 }}
    tier: filestore
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- range $key, $value := .Values.persistence.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- if not .Values.persistence.storageClass }}
  selector:
    matchLabels:
      app: {{ template "moodle.fullname" . }}
      stage: {{ .Values.stage }}
      tier: filestore
  {{- end }}
{{- end -}}
