{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.storageClass }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "moodle.fullname" . }}-app-pv
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
    tier: filestore
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- if .Values.persistence.resources }}
{{ toYaml .Values.persistence.resources | indent 2 }}
{{- end }}
{{- end }}
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "moodle.fullname" . }}-app-pvc
  {{- if or .Values.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
    tier: filestore
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if not .Values.persistence.storageClass }}
  selector:
    matchLabels:
      {{- include "moodle.selectorLabels" . | nindent 6 }}
      tier: filestore
  {{- end }}
{{- end -}}
