{{ if .Values.moodlePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "moodle.fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  {{- if not .Values.db.disableExternal }}
  {{- if .Values.db.auth.password }}
  db_password: {{ .Values.db.auth.password | b64enc | quote }}
  {{- else }}
  db_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.moodlePassword }}
  moodle_password: {{ .Values.moodlePassword | b64enc | quote }}
  {{- else }}
  moodle_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  smtp_password: {{ default "" .Values.smtpPassword | b64enc | quote }}
{{- end }}

{{ if .Values.shib.sp.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "moodle.fullname" . }}-shibd
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  sp-cert.pem: {{ .Values.shib.sp.cert | b64enc | quote }}
  sp-key.pem: {{ .Values.shib.sp.key | b64enc | quote }}
{{- end }}
