apiVersion: v1
kind: Secret
metadata:
  name: {{ template "moodle.fullname" . }}
  labels:
    {{- include "common_labels" . | indent 4 }}
type: Opaque
data:
  {{- if not .Values.db.disableExternal }}
  {{- if .Values.db.db.password }}
  db_password: {{ .Values.db.db.password | b64enc | quote }}
  {{- else }}
  db_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.moodlePassword }}
  moodle_password: {{ .Values.moodlePassword | b64enc | quote }}
  {{- else }}
  moodle_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  smtp_password: {{ default "" .Values.smtpPassword | b64enc | quote }}
