{{- if or (and (not .Values.db.enabled) .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecret)) (not .Values.moodleExistingSecret) (and .Values.smtp.password (not .Values.smtp.existingPassword)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle.fullname" . }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.db.enabled) .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecret) }}
  db_password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.moodleExistingSecret }}
  moodle_password: {{ .Values.moodlePassword | default (randAlphaNum 10) | b64enc | quote }}
  {{- end }}
  {{- if and .Values.smtp.password (not .Values.smtp.existingPassword) }}
  smtp_password: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}

{{ if .Values.shib.sp.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle.fullname" . }}-shibd
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
type: Opaque
data:
  sp-cert.pem: {{ .Values.shib.sp.cert | b64enc | quote }}
  sp-key.pem: {{ .Values.shib.sp.key | b64enc | quote }}
{{- end }}