apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.CI_PIPELINE_ID }}
    autodeployed: "true"
    pipeline_id: "{{  .Values.CI_PIPELINE_ID }}"
    {{- end }}
    {{- if .Values.CI_BUILD_ID }}
    build_id: "{{ .Values.CI_BUILD_ID }}"
    {{- end }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        stage: {{ .Values.stage }}
        tier: mysql
    spec:
      containers:
      - name: {{ .Chart.Name }}-mysql
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql_password
        - name: MYSQL_DATABASE
          value: {{ .Values.dbName | quote }}
        - name: MYSQL_USER
          value: {{ .Values.dbUsername | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql_password
        ports:
        - containerPort: 3306
      {{- if .Values.db.persistence.enabled }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-db-pvc
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    app: {{ template "fullname" . }}
    stage: {{ .Values.stage }}
    tier: mysql
spec:
  ports:
    - port: {{ .Values.dbPort }}
  selector:
    app: {{ template "fullname" . }}
    stage: {{ .Values.stage }}
    tier: mysql
