## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

stage: dev
replicas: 1
#debug: true
## Moodle image version
## ref: https://hub.docker.com/r/lthub/moodle/tags/
##
image:
  repository: lthub/moodle
  # tag:
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Specify a imagePullPolicy
## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## User of the application
## ref: https://github.com/bitnami/bitnami-docker-moodle#configuration
##
moodleUsername: user

## Application password
## Defaults to a random 10-character alphanumeric string if not set
##
# moodlePassword:

## Admin email
## ref: https://github.com/bitnami/bitnami-docker-moodle#configuration
moodleEmail: user@example.com

## No Reply Address
# moodleNoReplyAddress: noreply@example.com

## Set to `yes` to allow the container to be started with blank passwords
## ref: https://github.com/bitnami/bitnami-docker-moodle#environment-variables
allowEmptyPassword: "yes"

moodleFullName: "Moodle"

moodleShortName: "Moodle"

## SMTP mail delivery configuration
## ref: https://github.com/bitnami/bitnami-docker-moodle/#smtp-configuration
# smtpHost:
# smtpPort:
# smtpUser:
# smtpPassword:
# smtpProtocol:
# smtpAuth:

uploadMaxFileSize: &uploadMaxFileSize 20m

phpMemoryLimit: 128M

# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
##
## MariaDB chart configuration
##
## https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml
##
db:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  disableExternal: true
  ## Disable MariaDB replication
  replication:
    enabled: false
  # use default image from upstream
  #image:
  #  tag: 10.2
  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    type: mariadb
    name: &dbName moodle
    user: &dbUser moodle
    #prefix:

    ## If the password is not specified, mariadb will generates a random password
    ##
    # password: &dbPass

  ## MariaDB admin password
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  # rootUser:
  #   password:

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      expire-logs-days=90

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

  slave:
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      expire-logs-days=90

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

  service:
    # uncomment name to use external service
    #name:
    #endpoints:
    #  - 10.0.0.1
    #  - 10.0.0.2
    port: 3306

  ## Define affinity for the pod
  ## Sometimes required when persistent volumes are defined externally
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: node-role.kubernetes.io/master
#            operator: Exists
#            values:
#            - machine01
#      preferredDuringSchedulingIgnoredDuringExecution:
#      - weight: 1
#        preference:
#          matchExpressions:
#          - key: another-node-label-key
#            operator: In
#            values:
#            - another-node-label-value
#
#  resources:
#    requests:
#      memory: 768Mi
#      cpu: 750m

ubcCoursePayment:
  enabled: false
  db:
    # the db is on the same server as moodle. only define db name here
    name: Moodle_Payments
  uploadDir: /var/www/html/ubc_course_payments/locked/course_payments/supervisor_payment_info/uploaded_files/
  cbm:
    debug: true
    logfile: /tmp/cbm_error.log
    # url to the authen service
    authUrl: https://cbm.server/authServer/authenticate
    # url to web service
    pymtUrl: https://cbm.server/creditcardservice/CreditCardPaymentForm
    userId: abcdefg
    credential: abcdef
    srceTypCd: ABCD
  email:
    # email addr for sending out notifications
    from: sender@example.com
    # email addr for receiving copies of notification
    rmsRecipient: rmsRecipient@example.com
    # email addr for sending out flu clinic notifications
    immunization: immunization@example.com
    # email addr for receiving copies of flu clinic notification
    immunizationRecipient: immunizationRecipient@example.com
    # email addr included in notifications in which JV should be sent to
    jvRecipient: jvRecipient@example.com
    # email addr displayed on JCart pages in which JV should be sent to
    jcartJvRecipient: jcartJvRecipient@example.com
    # email addr of the web site admin
    websiteAdmin: websiteAdmin@example.com
  fitTest:
    moodleCourseId: 0

## Kubernetes configuration
## For minikube, set this to NodePort, for ingress ClusterIP, elsewhere use LoadBalancer
##
service:
  type: ClusterIP
  # HTTP Port
  port: 80
  # HTTPS Port
  httpsPort: 443
  ##
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  ##   https: <to set explicitly, choose port between 30000-32767>
  nodePorts:
    http: ""
    https: ""
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  externalPort: 80
  internalPort: 80


## Configure the ingress resource that allows you to access the
## Moodle installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  enabled: false

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - moodle.local

    ## Set this to true in order to enable TLS on the ingress record
    ## A side effect of this will be that the backend moodle service will be connected at port 443
#    tls: false

    ## Set this to true in order to add the corresponding annotations for cert-manager
#    certManager: false

    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
#    tlsSecret: moodle.local-tls

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: *uploadMaxFileSize

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: moodle.local-tls
  #   key:
  #   certificate:

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  accessMode: ReadWriteMany
  size: 8Gi
  # existingClaim: ""
  # resources:

## Define affinity for the moodle pod
## Sometimes required when persistent volumes are defined externally
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: node-role.kubernetes.io/master
#           operator: In
#           values:
#           - machine01
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 1
#       preference:
#         matchExpressions:
#         - key: another-node-label-key
#           operator: In
#           values:
#           - another-node-label-value

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  enabled: true
  method:
    httpGet:
      path: /login/index.php
      port: http
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  method:
    httpGet:
      path: /login/index.php
      port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}
## Prometheus Exporter / Metrics
##
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
     ## Metrics exporter pod Annotation and Labels
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}

cronjob:
  enabled: true
  schedule: "*/1 * * * *"

memcached:
  # enable internal memcached deployment and services, set to false to
  # use external memcached cluster
  enabled: false
  # Amount of memory allocated, for internal memcached deployment only
  memory: 64
  image:
    repository: memcached
    tag: 1.5-alpine
  # imagePullPolicy:
  replicas: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
  # memcached exporter for Prometheus
  exporter:
    enabled: false
    image:
      repository: quay.io/prometheus/memcached-exporter
      tag: latest
    # imagePullPolicy:
    resources:
      requests:
        memory: 16Mi
        cpu: 20m

redis:
  # enable internal redis deployment and services, set to false to
  # use external redis cluster
  enabled: false
  # db: 0
  # prefix: ''
  image:
    repository: redis
    tag: 5.0-alpine
  # imagePullPolicy:
  replicas: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
  # redis exporter for Prometheus
  exporter:
    enabled: false
    image:
      repository: oliver006/redis_exporter
      tag: latest
    # imagePullPolicy:
    resources:
      requests:
        memory: 16Mi
        cpu: 20m

  #jobrunner:
  #  enabled: false
  #  resources:
  #    requests:
  #      cpu: "50m"
  #      memory: "150Mi"

shib:
  enabled: false
  logLevel: INFO
  image:
    repository: lthub/shibd
    tag: latest
  port: 1600
  replicas: 1
  # imagePullPolicy:
  idp:
    discoveryUrl: https://example.com
    metadataUrl: https://example.com/idp/shibboleth
    entityId: https://example.com
    attributeMapUrl: https://example.com/attribute-map.xml
  sp:
    entityId: https://sp.example.com
    # key:
    # cert:
  odbc:
    driver: MySql
    lib: odbc-store.so
  resources:
    requests:
      memory: 64Mi
      cpu: 50m

