{{- if .Values.webworkFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webwork.fullname" . }}
  labels:
    {{- include "webwork.labels" . | nindent 4 }}
data:
  localOverrides: |
    {{ (.Values.webworkFiles).localOverrides | nindent 4 }}
  authen_saml2: |
    {{ (.Values.webworkFiles).authen_saml2 | nindent 4 }}
{{- end }}

{{- if .Values.shibd.idp.attribute_map }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webwork.fullname" . }}-cm
  labels:
    {{- include "webwork.labels" . | nindent 4 }}
data:
  attribute-map.xml: |
    {{ .Values.shibd.idp.attribute_map | nindent 4 }}
{{- end }}
