{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "webwork.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $hosts := append .Values.ingress.hosts .Values.CI_ENVIRONMENT_HOSTNAME | compact | uniq -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webwork.fullname" . }}
  labels:
    {{- include "webwork.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    {{- range $host := $hosts }}
    {{- $hostname := $host }}
    {{- $paths := list "/" }}
    {{- if not (kindIs "string" $host) }}
      {{- $hostname = $host.host }}
      {{- if $host.paths }}{{- $paths = $host.paths }}{{- end }}
    {{- end }}
    - host: {{ $hostname | quote }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
