{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "webwork.fullname" . }}
  labels:
    {{- include "webwork.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "webwork.selectorLabels" . | nindent 6 }}
      tier: app
{{- end }}
