apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ltic-access-request.fullname" . }}
  labels:
    {{- include "ltic-access-request.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ltic-access-request.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ltic-access-request.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.volumeMounts .Values.saml.enabled }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.saml.enabled }}
            - name: saml-certs
              mountPath: {{ .Values.saml.serviceProvider.certMountPath }}
              readOnly: true
            {{- end }}
          {{- end }}
          env:
            {{- include "ltic-access-request.podEnv" . | nindent 12 }}
      {{- if or .Values.volumes .Values.saml.enabled }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.saml.enabled }}
        - name: saml-certs
          secret:
            secretName: {{ include "ltic-access-request.fullname" . }}-saml
            items:
              - key: {{ .Values.saml.serviceProvider.keySecretKey }}
                path: {{ .Values.saml.serviceProvider.keyFilename }}
              - key: {{ .Values.saml.serviceProvider.certSecretKey }}
                path: {{ .Values.saml.serviceProvider.certFilename }}
              - key: {{ .Values.saml.serviceProvider.metadataSecretKey }}
                path: {{ .Values.saml.serviceProvider.metadataFilename }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
