{{- if .Values.saml.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ltic-access-request.fullname" . }}-saml
  labels:
    {{- include "ltic-access-request.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ required "externalSecret.secretStoreRefName must be set when saml.enabled is true" .Values.externalSecret.secretStoreRefName }}
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
  target:
    name: {{ include "ltic-access-request.fullname" . }}-saml
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.saml.serviceProvider.keySecretKey }}
      remoteRef:
        key: {{ .Values.saml.serviceProvider.externalSecretPath }}
        property: {{ .Values.saml.serviceProvider.externalSecretKeyProperty }}
    - secretKey: {{ .Values.saml.serviceProvider.certSecretKey }}
      remoteRef:
        key: {{ .Values.saml.serviceProvider.externalSecretPath }}
        property: {{ .Values.saml.serviceProvider.externalSecretCertProperty }}
    - secretKey: {{ .Values.saml.serviceProvider.metadataSecretKey }}
      remoteRef:
        key: {{ .Values.saml.serviceProvider.externalSecretPath }}
        property: {{ .Values.saml.serviceProvider.externalSecretMetadataProperty }}
{{- end }}
