{{- if .Values.cronjob.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ipeer.fullname" . }}-backup-cronjob
spec:
  schedule: {{ .Values.cronjob.backup.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "ipeer.fullname" . }}-backup-cronjob
            image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
            args:
            - /bin/sh
            - -c
            - |
              set -e
              echo "[$(date)] - Starts backing up ipeer database!"
              CURRENT_YEAR=$(date +%Y)
              MYSQLDMP_FILE=/db_archives/$CURRENT_YEAR/$IPEER_ENV_NAME-db-$(date +%F_%T).sql.gz
              mkdir -p /db_archives/$CURRENT_YEAR
              mysqldump -u"$IPEER_DB_USER" -p"$IPEER_DB_PASSWORD" -h"$IPEER_DB_HOST" ipeer --single-transaction --quick | gzip > $MYSQLDMP_FILE
              zgrep "Dump completed" $MYSQLDMP_FILE
            env:
            - name: IPEER_ENV_NAME
              value: {{ include "ipeer.fullname" . }}
            - name: IPEER_DB_HOST
              value: {{ template "ipeer.db.fullname" . }}
            - name: IPEER_DB_PORT
              value: {{ .Values.db.service.port | quote }}
            - name: IPEER_DB_USER
              value: {{ .Values.db.auth.username | quote }}
            - name: IPEER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.db.disableExternal }}
                  name: {{ template "ipeer.db.secretName" . }}
                  key: mariadb-password
                {{- else }}
                  name: {{ template "ipeer.fullname" . }}
                  key: db_password
                {{- end }}
            volumeMounts:
            - mountPath: /db_archives
              name: nfs-volume
          restartPolicy: Never
          volumes:
          - name: nfs-volume
            nfs:
              path: {{ .Values.cronjob.backup.nfs.path | quote }}
              server: {{ .Values.cronjob.backup.nfs.server | quote }}
{{- end }}
