{{- $hosts := .Values.ingress.hosts | compact | uniq -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "orchard.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key  }}: {{ $value | quote  }}
    {{- end }}
spec:
  rules:
  {{- $servicePrefix := include "orchard.fullname" . -}}
  {{- range $host := $hosts }}
  - host: {{ replace "http://" "" $host }}
    http:
      paths:
      - backend:
          serviceName: {{ $servicePrefix }}-ui-service
          servicePort: 80
        path: /(.*)
      - backend:
          serviceName: {{ $servicePrefix }}-api-service
          servicePort: 80
        path: /api(/|$)(.*)
  {{- end }}
  {{- if and (hasKey .Values.ingress.annotations "kubernetes.io/tls-acme") (eq (index .Values.ingress.annotations "kubernetes.io/tls-acme") "true") }}
  tls:
  - hosts:
    {{- range $host := $hosts }}
    - {{ replace "http://" "" $host }}
    {{- end }}
    secretName: {{ template "orchard.fullname" . }}-tls
  {{- end }}
