apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "orchard.fullname" . }}
spec:
  replicas: {{ .Values.replicas.ui }}
  selector:
    matchLabels:
      app: {{ template "orchard.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "orchard.fullname" . }}
    spec:
      containers:
        - name: {{ template "orchard.fullname" . }}
          image: {{ .Values.image.ui | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
