# Default values for compair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
stage: dev
dbPort: "3306"
dbName: alchemy
dbUsername: alchemy
dbPassword: PLEASE_CHANGE_ME
adminDefaultPassword: PLEASE_CHANGE_ME
appLoginEnabled: true
casLoginEnabled: false
casServer: null
casServiceValidateUrl: null
secret: PLEASE_CHANGE_ME
gaTrackingId: null

iframe:
  enabled: false
  origin: null

# xapi settings
xapi:
  enabled: false
  appBaseURL: https://archive.org/services/purl/alchemy/ctlt/
  lrsStatementEndpoint: https://lrs.example.com/data/xAPI/
  lrsActorAccountUseCas: false
  lrsActorAccountCasIdentifier: uid
  lrsActorAccountCasHomepage: http://www.example.com/
  lrsUsername: lrs
  lrsPassword: LRS_PASSWORD

app:
  replicaCount: 1
  image:
    repository: ubcctlt/alchemy
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    # auto provision
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 10Gi
    # NFS
    #accessMode: ReadWriteMany
    #resources:
    #  nfs:
    #    server: NSF_SERVER_IP
    #    path: "/export/data/alchemy"
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  ingress:
    enabled: true
    class: nginx
    #host: alchemy.example.com
    nginx:
      #configuration: null

worker:
  replicaCount: 1
  image:
    repository: ubcctlt/alchemy
    # should be passed through API variables
    #tag: latest
    pullPolicy: Always

db:
  image:
    repository: mariadb
    tag: 10.1
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 8Gi

redis:
  image:
    repository: redis
    tag: 3.2.4
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: false
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 1Gi