# Default values for compair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
stage: dev
dbPort: "3306"
dbName: alchemy
dbUsername: alchemy
dbPassword: PLEASE_CHANGE_ME
adminDefaultPassword: PLEASE_CHANGE_ME
appLoginEnabled: true
casLoginEnabled: false
casServer: null
casServiceValidateUrl: null
secret: PLEASE_CHANGE_ME
gaTrackingId: null

imagePullSecrets: []

iframe:
  enabled: false
  origin: null

# xapi settings
xapi:
  enabled: false
  appBaseURL: https://archive.org/services/purl/alchemy/ctlt/
  lrsStatementEndpoint: https://lrs.example.com/data/xAPI/
  lrsActorAccountUseCas: false
  lrsActorAccountCasIdentifier: uid
  lrsActorAccountCasHomepage: http://www.example.com/
  lrsUsername: lrs
  lrsPassword: LRS_PASSWORD

app:
  replicaCount: 1
  image:
    repository: ubcctlt/alchemy
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    # auto provision
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 10Gi
    # NFS
    #accessMode: ReadWriteMany
    #resources:
    #  nfs:
    #    server: NSF_SERVER_IP
    #    path: "/export/data/alchemy"
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  ingress:
    enabled: true
    class: nginx
    #host: alchemy.example.com
    nginx:
      configuration:
    annotations: {}
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

worker:
  replicaCount: 1
  image:
    repository: ubcctlt/alchemy
    tag: latest
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

db:
  image:
    repository: mariadb
    tag: 10.1
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 8Gi
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

redis:
  image:
    repository: redis
    tag: 3.2.4
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: false
    #storageClass: fast
    #accessMode: ReadWriteOnce
    #size: 1Gi
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
