apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
      - name: {{ template "app.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 2
          periodSeconds: 60
        env:
          - name: APP_NAME
            value: {{ .Values.app.name | quote }}
          - name: APP_ENV
            value: {{ .Values.app.mode | quote }}
          - name: APP_KEY
            value: {{ .Values.app.key | quote }}
          - name: APP_DEBUG
            value: {{ .Values.app.debug | quote }}
{{- if and (hasKey .Values.ingress.annotations "kubernetes.io/tls-acme") (eq (index .Values.ingress.annotations "kubernetes.io/tls-acme") "true") }}
          - name: APP_URL
            value: "https://{{ .Values.ingress.host }}"
          - name: FORCE_HTTPS
            value: "true"
{{- else }}
          - name: APP_URL
            value: "http://{{ .Values.ingress.host }}"
{{- end }}
          - name: DB_CONNECTION
            value: "pgsql"
          - name: DB_HOST
            value: {{ .Values.postgres.host | quote }}
          - name: DB_PORT
            value: {{ .Values.postgres.port | quote }}
          - name: DB_DATABASE
            value: {{ .Values.postgres.database | quote }}
          - name: DB_USERNAME
            value: {{ .Values.postgres.username | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.postgres.password | quote }}
          - name: FAKE_EMAIL_DOMAIN
            value: {{ .Values.app.fakeEmailDomain | quote }}
          - name: SESSION_DRIVER
            value: {{ .Values.app.session.driver | quote }}
          - name: SANCTUM_STATEFUL_DOMAINS
            value: {{ .Values.ingress.host  | quote }}
          - name: ADMIN_NAME
            value: {{ .Values.admin.name | quote }}
          - name: ADMIN_EMAIL
            value: {{ .Values.admin.email | quote }}
          - name: ADMIN_PASSWORD
            value: {{ .Values.admin.password | quote }}
