apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}-postgres
    spec:
      containers:
      - name: {{ template "app.fullname" . }}-postgres
        image: "postgres:alpine"
        ports:
          - containerPort: {{ .Values.postgres.port }}
        env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.password }}
            #      initContainers:
            #        - name: wait-for-laravel-env-replacement
            #          image: alpine
            #          command: ['sleep', '10']
