apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "app.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key  }}: {{ $value | quote  }}
    {{- end }}
spec:
  rules:
  - host: {{ replace "http://" "" .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "app.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: {{ replace "http://" "" .Values.ltijs.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "app.fullname" . }}-ltijs
            port:
              number: {{ .Values.ltijs.port }}
        path: /
        pathType: Prefix
  {{- if and (hasKey .Values.ingress.annotations "kubernetes.io/tls-acme") (eq (index .Values.ingress.annotations "kubernetes.io/tls-acme") "true") }}
  tls:
    - hosts:
      - {{ replace "http://" "" .Values.ingress.host }}
      - {{ replace "http://" "" .Values.ltijs.host }}
      - {{ replace "http://" "" .Values.mail.host }}
      secretName: {{ template "app.fullname" . }}-tls
  {{- end }}
