apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-mail
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.mail.relay.whitelist }}
spec:
  selector:
    app: {{ template "app.fullname" . }}-mail
  ports:
    - port: {{ .Values.mail.port }}
