apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-mail
  annotations:
    # mail relay servers are 10.19.216.31 to 10.19.216.41
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.19.216.1/24"
spec:
  selector:
    app: {{ template "app.fullname" . }}-mail
  ports:
    - port: {{ .Values.mail.port }}
