apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-mail
spec:
  selector:
    app: {{ template "app.fullname" . }}-mail
  # whitelist only internal IPs
  # mail relay servers are 10.19.216.31 to 10.19.216.41
  # also allow from within kube cluster?
  loadBalancerSourceRanges:
    - 10.0.0.0/8
  ports:
    - port: {{ .Values.mail.port }}
