apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-ltijs-mongo
spec:
  selector:
    app: {{ template "app.fullname" . }}-ltijs-mongo
  ports:
    - port: {{ .Values.ltijs.db.port }}
