{{- range .Values.databases }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "mariadb.fullname" $ }}-{{ .user }}
spec:
  name: {{ .user }}
  mariaDbRef:
    name: {{ include "mariadb.fullname" $ }}
  passwordSecretKeyRef:
    name: {{ include "mariadb.fullname" $ }}-user-password
    key: password-{{ .user }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ .user }}-grant
spec:
  mariaDbRef:
    name: {{ include "mariadb.fullname" $ }}
  username: {{ .user }}
  database: {{ .name }}
  privileges:
  - "ALL PRIVILEGES"
{{- end }}

{{- if and .Values.auth.username .Values.auth.database }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "mariadb.fullname" . }}-{{ .Values.auth.username }}-all
spec:
  name: {{ .Values.auth.username }}
  host: "%"
  mariaDbRef:
    name: {{ include "mariadb.fullname" . }}
  passwordSecretKeyRef:
    name: {{ include "mariadb.fullname" . }}-user-password
    key: password-{{ .Values.auth.username }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ include "mariadb.fullname" . }}-{{ .Values.auth.username }}-grant
spec:
  mariaDbRef:
    name: {{ include "mariadb.fullname" . }}
  username: {{ .Values.auth.username }}
  database: {{ .Values.auth.database }}
  privileges:
  - "ALL PRIVILEGES"
{{- end }}
