apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- if .Values.auth.existingSecret }}
  rootPasswordSecretKeyRef:
    name: {{ .Values.auth.existingSecret }}
    key: {{ .Values.auth.secretKeys.rootPasswordKey }}
  {{- end }}
  replicas: {{ if eq .Values.architecture "replication" }}{{ .Values.secondary.replicaCount }}{{ else }}1{{ end }}
  replicasAllowEvenNumber: true
  port: {{ .Values.primary.containerPorts.mysql }}
  storage:
    size: {{ .Values.persistence.size }}
  myCnf: |
{{ .Values.myCnf | indent 4 }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}

  {{- if eq .Values.architecture "replication" }}
  replication:
    enabled: true
    replicas: {{ .Values.secondary.replicaCount }}
    {{- if .Values.replication.semiSync.enabled }}
    semiSync:
      ackReplicas: {{ .Values.replication.semiSync.ackReplicas }}
    {{- end }}
  {{- end }}

  {{- if .Values.backup.enabled }}
  backup:
    schedule:
      cron: "{{ .Values.backup.schedule }}"
    storage:
      volumeClaimTemplate:
        resources:
          requests:
            storage: {{ .Values.backup.storage.size }}
        accessModes:
          {{- toYaml .Values.backup.storage.accessModes | nindent 10 }}
    retention:
      keep: {{ .Values.backup.retention.keep }}
  {{- end }}

  {{- if .Values.metrics.enabled }}
  metrics:
    exporter:
      image:
        repository: {{ .Values.metrics.exporter.image.repository }}
        tag: {{ .Values.metrics.exporter.image.tag }}
        pullPolicy: {{ .Values.metrics.exporter.image.pullPolicy }}
    {{- if .Values.metrics.serviceMonitor.enabled }}
    serviceMonitor:
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    {{- end }}
  {{- end }}
