apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- if .Values.auth.existingSecret }}
  rootPasswordSecretKeyRef:
    name: {{ .Values.auth.existingSecret }}
    key: {{ .Values.auth.secretKeys.rootPasswordKey }}
  {{- end }}
  port: {{ .Values.primary.containerPorts.mysql }}
  storage:
    size: {{ .Values.persistence.size }}
  myCnf: |
{{ .Values.myCnf | indent 4 }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}

  {{- if eq .Values.architecture "replication" }}
  replicas: {{ .Values.secondary.replicaCount }}
  replicasAllowEvenNumber: true
  replication:
    enabled: true
    primary:
      autoFailover: {{ .Values.primary.automaticFailover }}
    replica:
      replPasswordSecretKeyRef:
        name: {{ include "mariadb.fullname" . }}-user-password
        key: password-repl
    {{- if .Values.secondary.semiSync.enabled }}
    semiSyncEnabled: true
    semiSyncAckTimeout: 10s
    semiSyncWaitPoint: AfterCommit
    syncBinlog: 1
    {{- end }}
  primaryService:
    type: {{ .Values.primary.service.type }}
    metadata:
      annotations:
        {{- toYaml .Values.primary.service.annotations | nindent 12 }}
  secondaryService:
    type: {{ .Values.secondary.service.type }}
    metadata:
      annotations:
        {{- toYaml .Values.secondary.service.annotations | nindent 12 }}
  {{- end }}

  {{- if .Values.bootstrapFrom }}
  bootstrapFrom:
    {{-toYaml .Values.bootstrapFrom | nindent 4 }}
  {{- end }}

  service:
    type: {{ .Values.service.type }}
    metadata:
      annotations:
        {{- toYaml .Values.service.annotations | nindent 12 }}

  {{- if .Values.metrics.enabled }}
  metrics:
    exporter:
      image:
        repository: {{ .Values.metrics.exporter.image.repository }}
        tag: {{ .Values.metrics.exporter.image.tag }}
        pullPolicy: {{ .Values.metrics.exporter.image.pullPolicy }}
    {{- if .Values.metrics.serviceMonitor.enabled }}
    serviceMonitor:
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    {{- end }}
  {{- end }}
