apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  imagePullSecrets:
    {{- .Values.image.pullSecrets | default .Values.imagePullSecrets | toYaml | nindent 4 }}
  {{- if and .Values.auth.existingSecret .Values.auth.rootPasswordKey }}
  rootPasswordSecretKeyRef:
    name: {{ .Values.auth.existingSecret }}
    key: {{ .Values.auth.rootPasswordKey }}
  {{- end }}
  port: {{ .Values.primary.containerPorts.mysql }}
  storage:
    size: {{ .Values.persistence.size }}
    {{- if .Values.persistence.storageClassName }}
    storageClassName: {{ .Values.persistence.storageClassName }}
    {{- end }}
    {{- if .Values.persistence.ephemeral }}
    ephemeral: true
    {{- end }}
  myCnf: |
{{ .Values.myCnf | indent 4 }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}

  {{- if eq .Values.architecture "replication" }}
  replicas: {{ .Values.replicas }}
  replicasAllowEvenNumber: true
  replication:
    enabled: true
    primary:
      autoFailover: {{ .Values.primary.automaticFailover }}
    replica:
      replPasswordSecretKeyRef:
        name: {{ include "mariadb.fullname" . }}-user-password
        key: password-repl
    {{- if .Values.secondary.semiSync.enabled }}
    semiSyncEnabled: true
    semiSyncAckTimeout: 10s
    semiSyncWaitPoint: AfterCommit
    syncBinlog: 1
    {{- end }}
  primaryService:
    type: {{ .Values.primary.service.type }}
    metadata:
      annotations:
        {{- toYaml .Values.primary.service.annotations | nindent 12 }}
  secondaryService:
    type: {{ .Values.secondary.service.type }}
    metadata:
      annotations:
        {{- toYaml .Values.secondary.service.annotations | nindent 12 }}
  {{- end }}

  {{- if .Values.bootstrapFrom }}
  bootstrapFrom:
    {{- toYaml .Values.bootstrapFrom | nindent 4 }}
  {{- end }}

  service:
    type: {{ .Values.service.type }}
    metadata:
      annotations:
        {{- toYaml .Values.service.annotations | nindent 12 }}

  {{- if .Values.metrics.enabled }}
  metrics:
    enabled: true
    exporter:
      image: {{ .Values.metrics.exporter.image }}
      imagePullPolicy: {{ .Values.metrics.exporter.imagePullPolicy }}
      imagePullSecrets:
        {{- .Values.metrics.exporter.imagePullSecrets | default .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- if .Values.metrics.exporter.resources }}
      resources:
        {{- toYaml .Values.metrics.exporter.resources | nindent 8 }}
      {{- end }}
    serviceMonitor:
      # prometheusRelease: kube-prometheus-stack
      jobLabel: {{ include "mariadb.fullname" . }}-monitoring
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    {{- if .Values.metrics.username }}
    username: {{ .Values.metrics.username }}
    {{- end }}
    {{- if .Values.metrics.passwordSecretKeyRef }}
    passwordSecretKeyRef:
      {{- toYaml .Values.metrics.passwordSecretKeyRef | nindent 6 }}
    {{- end }}
  {{- end }}
