{{- $secretName := printf "%s-user-password" (include "mariadb.fullname" $) -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
stringData:
  {{- range .Values.databases }}
  {{- $password := "" -}}
  {{- if .password -}}
    {{- $password = .password -}}
  {{- else if (hasKey $secretData (printf "password-%s" .user)) -}}
    {{- $password = index $secretData (printf "password-%s" .user) | b64dec -}}
  {{- else -}}
    {{- $password = randAlphaNum 16 -}}
  {{- end }}
  password-{{ .user }}: {{ $password | quote }}
  {{- end }}
  {{- if and .Values.auth.username .Values.auth.database (not (and .Values.auth.existingSecret .Values.auth.userPasswordKey)) }}
  {{- $password := "" -}}
  {{- if .Values.auth.password -}}
    {{- $password = .Values.auth.password -}}
  {{- else if (hasKey $secretData (printf "password-%s" .Values.auth.username)) -}}
    {{- $password = index $secretData (printf "password-%s" .Values.auth.username) | b64dec -}}
  {{- else -}}
    {{- $password = randAlphaNum 16 -}}
  {{- end }}
  password-{{ .Values.auth.username }}: {{ $password | quote }}
  {{- end }}
  {{- if and (eq .Values.architecture "replication") (not (and .Values.auth.existingSecret .Values.auth.replPasswordKey)) }}
  {{- $password := "" -}}
  {{- if .Values.auth.replicationPassword -}}
    {{- $password = .Values.auth.replicationPassword -}}
  {{- else if (hasKey $secretData "password-repl") -}}
    {{- $password = index $secretData "password-repl" | b64dec -}}
  {{- else -}}
    {{- $password = randAlphaNum 16 -}}
  {{- end }}
  password-repl: {{ $password | quote }}
  {{- end }}
