---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" $ }}-user-password
stringData:
  {{- range .Values.databases }}
  password-{{ .user }}: {{ .password | default (randAlphaNum 16) | quote }}
  {{- end }}
  {{- if and .Values.auth.username .Values.auth.database }}
  password-{{ .Values.auth.username }}: {{ .Values.auth.password | default (randAlphaNum 16) | quote }}
  {{- end }}
  {{- if eq .Values.architecture "replication" }}
  password-repl: {{ .Values.auth.replicationPassword | default (randAlphaNum 16) | quote }}
  {{- end }}
