apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-nginx-service
spec:
  selector:
    app: {{ template "app.fullname" . }}-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
