apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}-nginx
    spec:
      containers:
      - name: {{ template "app.fullname" . }}-nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-nginx"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
