apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}-nginx
    spec:
      containers:
      - name: {{ template "app.fullname" . }}-nginx
        image: "{{ .Values.nginx.image.repo }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
