apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-node
spec:
  selector:
    matchLabels:
      app: {{ template "app.fullname" . }}-node
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "app.fullname" . }}-node
    spec:
      containers:
      - name: {{ template "app.fullname" . }}-node
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-node"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: "3Gi"
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: node-pv
            mountPath: /home/node/app/test-server/storage
      volumes:
        - name: node-pv
          persistentVolumeClaim:
            claimName: {{ template "app.fullname" . }}-node-pvc
