apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-node-service
spec:
  selector:
    app: {{ template "app.fullname" . }}-node
  ports:
  - name: http
    port: 80
    targetPort: 3000
