apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "canvas-bridge.fullname" . }}
  labels:
    {{- include "canvas-bridge.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
  target:
    name: {{ include "canvas-bridge.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: session-secret
      remoteRef:
        key: {{ .Values.externalSecret.path }}
        property: {{ .Values.externalSecret.properties.sessionSecret }}
    - secretKey: saml-sp-cert
      remoteRef:
        key: {{ .Values.externalSecret.path }}
        property: {{ .Values.externalSecret.properties.samlSpCert }}
    - secretKey: saml-sp-key
      remoteRef:
        key: {{ .Values.externalSecret.path }}
        property: {{ .Values.externalSecret.properties.samlSpKey }}
    - secretKey: saml-idp-cert
      remoteRef:
        key: {{ .Values.externalSecret.path }}
        property: {{ .Values.externalSecret.properties.samlIdpCert }}
