apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ print .Chart.Name "-" .Chart.Version | replace "+" "_" | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        stage: {{ .Values.stage | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum  }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: POSTGRES_DB_HOST
          value: {{ template "postgresql.fullname" . | default .Values.postgresql.service.name }}
        - name: POSTGRES_DB_PORT
          value: {{ .Values.postgresql.service.port | quote }}
        - name: POSTGRES_SCHEMA
          value: {{ .Values.postgresql.postgresDatabase | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: db_password
        - name: POSTGRES_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: admin_user
        - name: POSTGRES_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: admin_password
        - name: ADMIN_EMAIL
          value: {{ .Values.adminEmail }}
        - name: ADMIN_FIRSTNAME
          value: {{ .Values.adminFirstName }}
        - name: ADMIN_LASTNAME
          value: {{ .Values.adminLastName }}
        - name: ADMIN_PASSWORD
          value: {{ .Values.adminPassword }}
        - name: ADMIN_LANGUAGE
          value: {{ .Values.adminLanguage }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: {{ template "fullname" . }}-persistent-storage
          mountPath: /dspace/persistent
        {{- end }}
        - name: {{ template "fullname" . }}-config
          mountPath: /statspace-config
        livenessProbe:
          initialDelaySeconds: 240
          periodSeconds: 10
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # symbol link the config file as the file can't be project to config directory directly
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  ln -fs /statspace-config/dspace.cfg /dspace/config/dspace.cfg;
                  ln -fs /statspace-config/authentication-password.cfg /dspace/config/modules/authentication-password.cfg;
                  until nc -z localhost {{ .Values.service.internalPort }};
                  do
                    sleep 1;
                  done;
                  sleep 5;
                  dspace index-discovery
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: {{ template "fullname" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-app-pvc
      {{- end }}
      - name: {{ template "fullname" . }}-config
        configMap:
          name: {{ template "fullname" . }}-config
          items:
            - key: dspace.cfg
              path: dspace.cfg
            - key: authentication-password.cfg
              path: authentication-password.cfg
